/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AutologinRouteImport } from './routes/autologin'
import { Route as CashReportsRouteImport } from './routes/cash-reports'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CorporateReportsRouteImport } from './routes/corporate-reports'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GcecRouteImport } from './routes/gcec'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PayablesRouteImport } from './routes/payables'
import { Route as PosRouteImport } from './routes/pos'
import { Route as RafflesRouteImport } from './routes/raffles'
import { Route as RegisterStoreOwnerRouteImport } from './routes/register-store-owner'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as VitrineChatRouteImport } from './routes/vitrine-chat'
import { Route as VitrineSettingsRouteImport } from './routes/vitrine-settings'
import { Route as StoreSlugCustomersRouteImport } from './routes/$storeSlug.customers'
import { Route as StoreSlugDashboardRouteImport } from './routes/$storeSlug.dashboard'
import { Route as StoreSlugLoginRouteImport } from './routes/$storeSlug.login'
import { Route as StoreSlugPosRouteImport } from './routes/$storeSlug.pos'
import { Route as StoreSlugRegisterRouteImport } from './routes/$storeSlug.register'
import { Route as StoreSlugVitrineRouteImport } from './routes/$storeSlug.vitrine'
import { Route as LStoreSlugRouteImport } from './routes/l.$storeSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AutologinRoute = AutologinRouteImport.update({
  id: '/autologin',
  path: '/autologin',
  getParentRoute: () => rootRouteImport,
} as any)
const CashReportsRoute = CashReportsRouteImport.update({
  id: '/cash-reports',
  path: '/cash-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateReportsRoute = CorporateReportsRouteImport.update({
  id: '/corporate-reports',
  path: '/corporate-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GcecRoute = GcecRouteImport.update({
  id: '/gcec',
  path: '/gcec',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesRoute = PayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const RafflesRoute = RafflesRouteImport.update({
  id: '/raffles',
  path: '/raffles',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStoreOwnerRoute = RegisterStoreOwnerRouteImport.update({
  id: '/register-store-owner',
  path: '/register-store-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineChatRoute = VitrineChatRouteImport.update({
  id: '/vitrine-chat',
  path: '/vitrine-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineSettingsRoute = VitrineSettingsRouteImport.update({
  id: '/vitrine-settings',
  path: '/vitrine-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugCustomersRoute = StoreSlugCustomersRouteImport.update({
  id: '/$storeSlug/customers',
  path: '/$storeSlug/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugDashboardRoute = StoreSlugDashboardRouteImport.update({
  id: '/$storeSlug/dashboard',
  path: '/$storeSlug/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugLoginRoute = StoreSlugLoginRouteImport.update({
  id: '/$storeSlug/login',
  path: '/$storeSlug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugPosRoute = StoreSlugPosRouteImport.update({
  id: '/$storeSlug/pos',
  path: '/$storeSlug/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRegisterRoute = StoreSlugRegisterRouteImport.update({
  id: '/$storeSlug/register',
  path: '/$storeSlug/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugVitrineRoute = StoreSlugVitrineRouteImport.update({
  id: '/$storeSlug/vitrine',
  path: '/$storeSlug/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const LStoreSlugRoute = LStoreSlugRouteImport.update({
  id: '/l/$storeSlug',
  path: '/l/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autologin': typeof AutologinRoute
  '/cash-reports': typeof CashReportsRoute
  '/companies': typeof CompaniesRoute
  '/corporate-reports': typeof CorporateReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/gcec': typeof GcecRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/payables': typeof PayablesRoute
  '/pos': typeof PosRoute
  '/raffles': typeof RafflesRoute
  '/register-store-owner': typeof RegisterStoreOwnerRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vitrine': typeof VitrineRoute
  '/vitrine-chat': typeof VitrineChatRoute
  '/vitrine-settings': typeof VitrineSettingsRoute
  '/$storeSlug/customers': typeof StoreSlugCustomersRoute
  '/$storeSlug/dashboard': typeof StoreSlugDashboardRoute
  '/$storeSlug/login': typeof StoreSlugLoginRoute
  '/$storeSlug/pos': typeof StoreSlugPosRoute
  '/$storeSlug/register': typeof StoreSlugRegisterRoute
  '/$storeSlug/vitrine': typeof StoreSlugVitrineRoute
  '/l/$storeSlug': typeof LStoreSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autologin': typeof AutologinRoute
  '/cash-reports': typeof CashReportsRoute
  '/companies': typeof CompaniesRoute
  '/corporate-reports': typeof CorporateReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/gcec': typeof GcecRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/payables': typeof PayablesRoute
  '/pos': typeof PosRoute
  '/raffles': typeof RafflesRoute
  '/register-store-owner': typeof RegisterStoreOwnerRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vitrine': typeof VitrineRoute
  '/vitrine-chat': typeof VitrineChatRoute
  '/vitrine-settings': typeof VitrineSettingsRoute
  '/$storeSlug/customers': typeof StoreSlugCustomersRoute
  '/$storeSlug/dashboard': typeof StoreSlugDashboardRoute
  '/$storeSlug/login': typeof StoreSlugLoginRoute
  '/$storeSlug/pos': typeof StoreSlugPosRoute
  '/$storeSlug/register': typeof StoreSlugRegisterRoute
  '/$storeSlug/vitrine': typeof StoreSlugVitrineRoute
  '/l/$storeSlug': typeof LStoreSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/autologin': typeof AutologinRoute
  '/cash-reports': typeof CashReportsRoute
  '/companies': typeof CompaniesRoute
  '/corporate-reports': typeof CorporateReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/gcec': typeof GcecRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/payables': typeof PayablesRoute
  '/pos': typeof PosRoute
  '/raffles': typeof RafflesRoute
  '/register-store-owner': typeof RegisterStoreOwnerRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vitrine': typeof VitrineRoute
  '/vitrine-chat': typeof VitrineChatRoute
  '/vitrine-settings': typeof VitrineSettingsRoute
  '/$storeSlug/customers': typeof StoreSlugCustomersRoute
  '/$storeSlug/dashboard': typeof StoreSlugDashboardRoute
  '/$storeSlug/login': typeof StoreSlugLoginRoute
  '/$storeSlug/pos': typeof StoreSlugPosRoute
  '/$storeSlug/register': typeof StoreSlugRegisterRoute
  '/$storeSlug/vitrine': typeof StoreSlugVitrineRoute
  '/l/$storeSlug': typeof LStoreSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/autologin'
    | '/cash-reports'
    | '/companies'
    | '/corporate-reports'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/finance'
    | '/gcec'
    | '/inventory'
    | '/login'
    | '/messages'
    | '/payables'
    | '/pos'
    | '/raffles'
    | '/register-store-owner'
    | '/reports'
    | '/settings'
    | '/vitrine'
    | '/vitrine-chat'
    | '/vitrine-settings'
    | '/$storeSlug/customers'
    | '/$storeSlug/dashboard'
    | '/$storeSlug/login'
    | '/$storeSlug/pos'
    | '/$storeSlug/register'
    | '/$storeSlug/vitrine'
    | '/l/$storeSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/autologin'
    | '/cash-reports'
    | '/companies'
    | '/corporate-reports'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/finance'
    | '/gcec'
    | '/inventory'
    | '/login'
    | '/messages'
    | '/payables'
    | '/pos'
    | '/raffles'
    | '/register-store-owner'
    | '/reports'
    | '/settings'
    | '/vitrine'
    | '/vitrine-chat'
    | '/vitrine-settings'
    | '/$storeSlug/customers'
    | '/$storeSlug/dashboard'
    | '/$storeSlug/login'
    | '/$storeSlug/pos'
    | '/$storeSlug/register'
    | '/$storeSlug/vitrine'
    | '/l/$storeSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/autologin'
    | '/cash-reports'
    | '/companies'
    | '/corporate-reports'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/finance'
    | '/gcec'
    | '/inventory'
    | '/login'
    | '/messages'
    | '/payables'
    | '/pos'
    | '/raffles'
    | '/register-store-owner'
    | '/reports'
    | '/settings'
    | '/vitrine'
    | '/vitrine-chat'
    | '/vitrine-settings'
    | '/$storeSlug/customers'
    | '/$storeSlug/dashboard'
    | '/$storeSlug/login'
    | '/$storeSlug/pos'
    | '/$storeSlug/register'
    | '/$storeSlug/vitrine'
    | '/l/$storeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AutologinRoute: typeof AutologinRoute
  CashReportsRoute: typeof CashReportsRoute
  CompaniesRoute: typeof CompaniesRoute
  CorporateReportsRoute: typeof CorporateReportsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  FinanceRoute: typeof FinanceRoute
  GcecRoute: typeof GcecRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PayablesRoute: typeof PayablesRoute
  PosRoute: typeof PosRoute
  RafflesRoute: typeof RafflesRoute
  RegisterStoreOwnerRoute: typeof RegisterStoreOwnerRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  VitrineRoute: typeof VitrineRoute
  VitrineChatRoute: typeof VitrineChatRoute
  VitrineSettingsRoute: typeof VitrineSettingsRoute
  StoreSlugCustomersRoute: typeof StoreSlugCustomersRoute
  StoreSlugDashboardRoute: typeof StoreSlugDashboardRoute
  StoreSlugLoginRoute: typeof StoreSlugLoginRoute
  StoreSlugPosRoute: typeof StoreSlugPosRoute
  StoreSlugRegisterRoute: typeof StoreSlugRegisterRoute
  StoreSlugVitrineRoute: typeof StoreSlugVitrineRoute
  LStoreSlugRoute: typeof LStoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autologin': {
      id: '/autologin'
      path: '/autologin'
      fullPath: '/autologin'
      preLoaderRoute: typeof AutologinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-reports': {
      id: '/cash-reports'
      path: '/cash-reports'
      fullPath: '/cash-reports'
      preLoaderRoute: typeof CashReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-reports': {
      id: '/corporate-reports'
      path: '/corporate-reports'
      fullPath: '/corporate-reports'
      preLoaderRoute: typeof CorporateReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gcec': {
      id: '/gcec'
      path: '/gcec'
      fullPath: '/gcec'
      preLoaderRoute: typeof GcecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables': {
      id: '/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof PayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffles': {
      id: '/raffles'
      path: '/raffles'
      fullPath: '/raffles'
      preLoaderRoute: typeof RafflesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-store-owner': {
      id: '/register-store-owner'
      path: '/register-store-owner'
      fullPath: '/register-store-owner'
      preLoaderRoute: typeof RegisterStoreOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine-chat': {
      id: '/vitrine-chat'
      path: '/vitrine-chat'
      fullPath: '/vitrine-chat'
      preLoaderRoute: typeof VitrineChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine-settings': {
      id: '/vitrine-settings'
      path: '/vitrine-settings'
      fullPath: '/vitrine-settings'
      preLoaderRoute: typeof VitrineSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/customers': {
      id: '/$storeSlug/customers'
      path: '/$storeSlug/customers'
      fullPath: '/$storeSlug/customers'
      preLoaderRoute: typeof StoreSlugCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/dashboard': {
      id: '/$storeSlug/dashboard'
      path: '/$storeSlug/dashboard'
      fullPath: '/$storeSlug/dashboard'
      preLoaderRoute: typeof StoreSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/login': {
      id: '/$storeSlug/login'
      path: '/$storeSlug/login'
      fullPath: '/$storeSlug/login'
      preLoaderRoute: typeof StoreSlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/pos': {
      id: '/$storeSlug/pos'
      path: '/$storeSlug/pos'
      fullPath: '/$storeSlug/pos'
      preLoaderRoute: typeof StoreSlugPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/register': {
      id: '/$storeSlug/register'
      path: '/$storeSlug/register'
      fullPath: '/$storeSlug/register'
      preLoaderRoute: typeof StoreSlugRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/vitrine': {
      id: '/$storeSlug/vitrine'
      path: '/$storeSlug/vitrine'
      fullPath: '/$storeSlug/vitrine'
      preLoaderRoute: typeof StoreSlugVitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$storeSlug': {
      id: '/l/$storeSlug'
      path: '/l/$storeSlug'
      fullPath: '/l/$storeSlug'
      preLoaderRoute: typeof LStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AutologinRoute: AutologinRoute,
  CashReportsRoute: CashReportsRoute,
  CompaniesRoute: CompaniesRoute,
  CorporateReportsRoute: CorporateReportsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  FinanceRoute: FinanceRoute,
  GcecRoute: GcecRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PayablesRoute: PayablesRoute,
  PosRoute: PosRoute,
  RafflesRoute: RafflesRoute,
  RegisterStoreOwnerRoute: RegisterStoreOwnerRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  VitrineRoute: VitrineRoute,
  VitrineChatRoute: VitrineChatRoute,
  VitrineSettingsRoute: VitrineSettingsRoute,
  StoreSlugCustomersRoute: StoreSlugCustomersRoute,
  StoreSlugDashboardRoute: StoreSlugDashboardRoute,
  StoreSlugLoginRoute: StoreSlugLoginRoute,
  StoreSlugPosRoute: StoreSlugPosRoute,
  StoreSlugRegisterRoute: StoreSlugRegisterRoute,
  StoreSlugVitrineRoute: StoreSlugVitrineRoute,
  LStoreSlugRoute: LStoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
